### ISSUE TITLE
Supervisord & docker logs overflow the host filesystem

### ISSUE THREAD

**Issue by twirtgen** [nsg-ethz/mini_internet_project#24]
Hello,

We decided to run the mini-internet on a virtual machine with a small amount of storage (~30GB). Everything was going perfectly well until the virtual machine crashed. Upon investigation, I discovered that the file system was saturated with logs generated by the various services running the mini-internet:

- The mini_internet_project/platform/docker_images/base_supervisor/[logger.sh](https://github.com/nsg-ethz/mini_internet_project/blob/980d55c06bb129d647bf4ae75b198e71140701f6/platform/docker_images/base_supervisor/logger.sh) is used to gather all logs to the docker daemon. However, docker is not configured by default to limit the size of the logs and rotate them when they exceed the maximum size.
- The supervisord daemon also generates many logs for the daemons it supervises. [By default](http://supervisord.org/configuration.html?highlight=logfile_maxbytes#program-x-section-values), it rotates the logs when the log file size exceeds 50 MB. Logs for router daemons tend to be a bit verbose. The frr and looking_glass processes can generate more than 50 MB after 2 weeks. If the mini-internet is configured to run a large network of 70ASes, each with 8 routers like the configuration given on the wiki, a large amount of storage is required.

It would be nice to configure the docker daemon to limit the logs recorded with logger.sh. This can be done either in the startup.sh script or indicated in the wiki that docker should be manually configured to limit logs.

It could be also a good idea to limit the size of logs kept and the number of files rotated per container.

If keeping these logs is intentional, it would be worth to indicate in the wiki that a large amount of storage is required to run the mini-internet.

**Comment by twirtgen** [comment]
Thanks!

Hopefully, thanks to a Cron job that I setup every night to make backup of each container, I was able to rebuild the mini-internet and recover the configuration of each AS.  So nothing serious !

Also, when I was looking at this repository, I came across a [file](https://github.com/nsg-ethz/mini_internet_project/blob/master/platform/utils/miscellaneous/recover_ovs_flows.sh) that restore the state of Open vSwitch.
Is this script might have been used to restore the state of the mini-internet after a reboot of the host server ?
We can move this discussion on another issue if you want

**Comment by KTrel** [comment]
Great that you could recover the configuration of every AS!

This script was designed by an external contributor (see this [pull request](https://github.com/nsg-ethz/mini_internet_project/commit/dbcf3621994a1c53e8c367d66001c3f18e71864b)). Here, the switches that are restored are not the switches used by the students, but the switches used in every virtual links. In fact, when there is a link between  two virtual devices or hosts, there is actually an OvS switch in between (invisible from the students' perspective). This switch allows to e.g., control the bandwidth of the links or their delay without using `tc` in the hosts/routers/switches controlled by students. Thus, students cannot increase these values.

**Comment by KTrel** [comment]
It should be fixed now (see [here](https://github.com/nsg-ethz/mini_internet_project/commit/6966f39c2fcfb0a52135328647b29ecd747a474d)). Thanks again for reporting it.
