### ISSUE TITLE
Krill key is not created on group if Krill host is not first on l3_routers

### ISSUE THREAD

**Issue by Zeawiel** [nsg-ethz/mini_internet_project#25]
Hello,

First of all, thank you for this incredible platform! I'm using it with student, they like it!

I used old version (2019 or 2020) and I just updated it to the last one to have the website, rpki ...
I had an issue with config files that cause me headache.

It seems that the Krill host should be put in first in the l3_routers config file. Otherwise the key is not created into the group folder.

This works:
```
GENE    DNS krill:miniinterneteth/d_krill       vtysh
LOND    MATRIX	routinator:miniinterneteth/d_routinator	vtysh
ZURI    MATRIX_TARGET host:miniinterneteth/d_host	vtysh
``` 

This does not work (for me):
```
LOND    MATRIX	routinator:miniinterneteth/d_routinator	vtysh
ZURI    MATRIX_TARGET host:miniinterneteth/d_host	vtysh
GENE    DNS krill:miniinterneteth/d_krill       vtysh
``` 

I get 
`./setup/container_setup.sh: line 180: /home/xxxx/groups/g1/krill/kill_token.txt: No such file or directory`
and, juste before, during the `rpki_config.sh` script, it creates only the `groups/rpki/root.key`

That's quite strange. It didn't get through the code since it's way above my knowledge.

I hope I can help to make this platform even better with my little contribution :)

Have a nice day

**Comment by KTrel** [comment]
Hi. We are glad if the students like it :-) and sorry about the headache! :pray: 

I fixed the problem, you can see the fix in this [commit](https://github.com/nsg-ethz/mini_internet_project/commit/1fc06097db979c76f1b8a161cfe4bca428d0a9e2).

Thanks for reporting it! (and please let us know if you experience other issues)
