### ISSUE TITLE
Restart Docker containers

### ISSUE THREAD

**Issue by josephnoir** [nsg-ethz/mini_internet_project#30]
Hi,

we are running a deployment of the Mini Internet and for a reason I haven't figured out yet all docker containers died 9 hours ago.

Is there a way to recover from here without setting up a new Mini Internet (which resets passwords as well)?

Kind regards
Raphael

**Comment by NotSpecial** [comment]
You could try the wiki instructions to [restart a container](https://github.com/nsg-ethz/mini_internet_project/wiki/restart_container#restart-a-container).

I don't know what exactly happened to your docker setup, but maybe that will help you recover.

**Comment by NotSpecial** [comment]
Oh, that looks strange ... unfortunately I'm not quite sure how to deal with that.

Let me ping @KTrel , maybe he has an idea how to solve this.

**Comment by josephnoir** [comment]
I tried playing around with `docker commit` and then running new containers from the image. But I think I understand too little from the underlying setup. I'm a bit afraid to introduce problems that I will only discover later. So I will just redo the setup. I'd still be curious if there is a better way to fix this.

PS: This is a great project and so far the documentation has been very good. Great work!

**Comment by KTrel** [comment]
Hi,

I am not sure what happened, but I do not think you can recover the mini-Internet if all the containers have crashed. It is more reasonable to just start a new one. However, I would keep a copy of the `groups` directory where the router configurations are saved (in case students ask for them).

**Comment by josephnoir** [comment]
>  However, I would keep a copy of the groups directory where the router configurations are saved (in case students ask for them).

Oh, I did not do that. Would there be a way to restore those automatically, e.g., by copying the folders (or parts of them) back into the new directory? We do advise students to make backups of the configuration. So I hope they do indeed do that.
