### ISSUE TITLE
Connectivity Matrix not working

### ISSUE THREAD

**Issue by mark-hgb** [nsg-ethz/mini_internet_project#31]
Dear all,

I am using your Mini Internet Software for a lecture on Advanced Routing. It is just great, thanks for your efforts!

I currently have some troubles with the Connectivity Matrix feature. I start a Mini Internet with 24 ASes all fully configured ("Config" in C3 in "AS_config.txt"). The MATRIX container is working (unpause) and collecting data (I can see the files when connecting directly to the container). In the web frontend I get the message "Sorry, no data is available! Please check in later." when accessing the Connectivity Matrix feature (this originates from the Flask [?] template for this page). When looking at the webserver logs ("docker logs web") I get the following error all the time:

Traceback (most recent call last):
  File "/server/routing_project_server/app.py", line 280, in loop
    raise RuntimeError(
RuntimeError: Worker `prepare_matrix` crashed! Restarting.
Traceback (most recent call last):
  File "/server/routing_project_server/app.py", line 277, in loop
    function(*args, **kwargs)
  File "/server/routing_project_server/app.py", line 320, in prepare_matrix
    config['LOCATIONS']['matrix_stats']
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'matrix_stats'

AFAIK "matrix_stats" refers to a stats.txt file, which does exist on the MATRIX container but nowhere else. Any help would be much appreciated!

**Comment by NotSpecial** [comment]
Hi! First of all, I'm sorry for the inconvenience. We are currently in the progress of merging our latest updates back into the main branch (see #29 ). We mixed up some steps of the progress, and now the containers on docker hub are already updated while the branch is not yet merged. This leads to the errors you observe.

The issue you are facing comes from the fact that the setup scripts on the main branch do not make the stats file available to the web container.

You could do the following:
- Use the commnet-dev branch from the merge request above, which uses all updated files (soon part of the main branch)
- Copy over the [matrix](https://github.com/nsg-ethz/mini_internet_project/blob/commnet-23/platform/setup/matrix_setup.sh) and [website](https://github.com/nsg-ethz/mini_internet_project/blob/commnet-23/platform/setup/website_setup.sh) setup files from the dev branch to your local branch. With those two setup parts updated, the stats file should be available.

**Comment by mark-hgb** [comment]
Great, thanks for the fast reply! Using the commnet-23 (?) branch works like a charm, the Connectivity Matrix gets displayed now. One more question, since I use a fully configured test setup ("Config" in C3 in "AS_config.txt" for all ASes), I would expect to see full connectivity (everything green) in the Connectivitiy Matrix. But it isn't that way, everything is red, so no connectivity at all. Pinging hosts in one group from hosts in other groups is showing that there is full connectivity. Is this a bug or do I understand something wrong?

**Comment by mark-hgb** [comment]
Thx for the quick reply! Using the commnet-23 branch works like a charm, the Connectivity Matrix gets displayed now! Great!

**Comment by NotSpecial** [comment]
Happy to hear that!
