### ISSUE TITLE
Wiki: AS configuration link does not work

### ISSUE THREAD

**Issue by josephnoir** [nsg-ethz/mini_internet_project#33]
On the [configuration page](https://github.com/nsg-ethz/mini_internet_project/wiki/general_configuration#as_configtxt), the link pointing to the explanation for the config generation does not work.

> ℹ️ We automatically generate this file using a script, which we will [explain in a following section](https://github.com/nsg-ethz/mini_internet_project/ASlevel_configuration).

Here, `https://github.com/nsg-ethz/mini_internet_project/ASlevel_configuration` is missing `wiki` in its path. The correct link is probably: `https://github.com/nsg-ethz/mini_internet_project/wiki/ASlevel_configuration`.

I hoping reporting this here is ok. (I did not see an option to open a PR for the wiki.)

**Comment by NotSpecial** [comment]
Thank you for the notification, I have updated the link!
