### ISSUE TITLE
hard-coded username in save_history.sh 

### ISSUE THREAD

**Issue by josephnoir** [nsg-ethz/mini_internet_project#34]
In the branch `commnet-23` the script `platform/utils/gif/history_config.sh` uses a hard coded username to [perform the git commit & push](https://github.com/nsg-ethz/mini_internet_project/blob/commnet-23/platform/utils/gif/history_config.sh#L89). The variable for the username (`$USERNAME`) is available, but not used here.

**Comment by NotSpecial** [comment]
Thanks for the feedback, I've added the update to the comment branch and it will be merged soon, I hope.
