### ISSUE TITLE
Link delay not working

### ISSUE THREAD

**Issue by roellinl** [nsg-ethz/mini_internet_project#35]
Hi, I'm using the mini internet right now and found that the link delay is not working anymore. 
It seems to not work anymore because [tc-netem](https://man7.org/linux/man-pages/man8/tc-netem.8.html) needs the unit ms for the command to succeed. 
At the moment the command is run like that `tc qdisc add dev "${PORTNAME}"_l root netem delay "${DELAY}" ` which doesn't include the unit ms.

### 3 possible ways to fix it
1. Change all the config files where a delay is specified to include the unit ms. So if the config contained `100` before it should now be `100ms`. 
1. Change the code to add the unit automatically. This would be in the file **mini_internet_project/platform/setup/ovs-docker.sh** line 193 and 194. It would need to be changed from: 
``` 
if [ -n "$DELAY" ]; then
         echo "tc qdisc add dev "${PORTNAME}"_l root netem delay "${DELAY}" " >> groups/delay_throughput.sh
         echo "  tc qdisc add dev "${PORTNAME}"_l root netem delay "${DELAY}" " >> groups/restart_container.sh
fi
```
to:
``` 
if [ -n "$DELAY" ]; then
         echo "tc qdisc add dev "${PORTNAME}"_l root netem delay "${DELAY}ms" " >> groups/delay_throughput.sh
         echo "  tc qdisc add dev "${PORTNAME}"_l root netem delay "${DELAY}ms" " >> groups/restart_container.sh
fi
```
3. The third option would be to add the ms to the config file but have a test in the **mini_internet_project/platform/setup/ovs-docker.sh** file that will add the "ms" if it is missing to keep it compatible with previous configs.

If you decide on one of the options that change the config files then the wiki entries also need to be updated to reflect the changes.

On another note thanks a lot for providing access to the mini internet. It is a really amazing tool.

**Comment by NotSpecial** [comment]
I would vote for adding the ms to the config files; this will also make it clearer what the delay is.
I will update the current configs.

A quick question: is it obvious that the link delay is not working, i.e. is there an error message? Or does it fail silently?

**Comment by roellinl** [comment]
I can create a pull request with all the config files already changed if that makes it easier.

For the second part, it fails silently or at least I haven't seen any error messages.

**Comment by NotSpecial** [comment]
Actually, I should not have closed this yet. We still have the issue of the errors being silent.

I don't have much time to look at this right now; do you have any ideas how we could reliably check whether the inputs are actually working for `tc`?

**Comment by roellinl** [comment]
I don't really know but it seems to me that tc would print an error if run on its own and that there is no error showing up because the output of the delay_throughput.sh script is silenced in the startup.sh script.
